server:
  port: 8004

spring:
  application:
    name: service-cms #服务名
  profiles:
    active: dev #服务环境
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    password: 12345
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    password: xzq12345
    host: 47.107.116.102
    port: 6379
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
mybatis-plus:
  mapper-locations: classpath:com/xiangge/educms/mapper/xml/*.xml












