server:
  port: 8003
spring:
  profiles:
    active: dev
  application:
    name: service-vod
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  vod:
    file:
      keyid: LTAI5t7ACfNm3TyyvWRnsJRt
      keysecret: JBmkIiO0PbpbBCM5OQt8ITcM9TAq5t
