server:
  port: 8160

spring:
  application:
    name: service-ucenter #服务名
  profiles:
    active: dev #服务环境
  datasource:
    password: 12345
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?characterEncoding=utf-8&useSSL=false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    password: xzq12345
    host: 47.107.116.102
    port: 6379
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
mybatis-plus:
  mapper-locations: classpath:com/xiangge/educenter/mapper/xml/*.xml

wx:
  open.app_id: wxed9954c01bb89b47
  # 微信开放平台 appsecret
  open.app_secret: a7482517235173ddb4083788de60b90e
  # 微信开放平台 重定向url
  open.redirect_url: http://localhost:8160/api/ucenter/wx/callback









